spring.application.name=tienda
server.port=8084

# URL de los microservicios externos
productos.api.url=http://localhost:8081/productos
usuarios.api.url=http://localhost:8082/usuarios
pedidos.api.url=http://localhost:8083/pedidos
