spring.application.name=tienda
server.port=8084

api.urls.productos=http://localhost:8081/productos
api.urls.usuarios=http://localhost:8082/usuarios
api.urls.pedidos=http://localhost:8083/pedidos

spring.main.allow-bean-definition-overriding=true
